name: CI

on: [push, pull_request]

jobs:

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up proper version of Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.1
        id: go

      - name: run tests
        run: make test
